### PR TITLE
Native image cross arch docker build support

### PR DESCRIPTION
**Pull request by micossow**

### CODE REVIEW

**Comment by micossow** [comment]
closes #724

**Comment by adamw** [comment]
That's hard to review as I never really implemented sth like that, I can only suggest merging & doing an RC release to verify if this works, otherwise iterate on a fix :). My only question I suppose would be, where's the `buildx` invocation?

**Comment by micossow** [comment]
> That's hard to review as I never really implemented sth like that, I can only suggest merging & doing an RC release to verify if this works, otherwise iterate on a fix :). My only question I suppose would be, where's the `buildx` invocation?

It has been verified with https://github.com/softwaremill/elasticmq/releases/tag/v1.4.5-RC2
`buildx` is configured in `dockerBuildxSettings`

**Comment by adamw** [comment]
@micossow Well if it's verified, then ship it :)

**Pull request merged**
