### PR TITLE
Changed regex to match queue URL format.

### PR DESCRIPTION
**Pull request by Opalo**
Related to #122 and #166.

### CODE REVIEW

**Comment by adamw** [comment]
How about a test? You could create a queue (using the sqs sdk), and then issue a request to a hand-craft URL using an account number

**Comment by Opalo** [comment]
@adamw test is in progress ;) Could you please give more detailed description of the test?

**Comment by adamw** [comment]
sth like here: https://github.com/softwaremill/elasticmq/blob/develop/rest/rest-sqs-testing-amazon-java-sdk/src/test/scala/org/elasticmq/rest/sqs/AmazonJavaSdkTestSuite.scala#L140-L149, only not deleting the queue but checking that it exists using a hand-created URL

**Comment by Opalo** [comment]
Cool! That's what I thought :)

**Pull request merged**
